# Offense count: 8
Style/AccessorMethodName:
  Exclude:
    - 'easybib/tests/test_config.rb'
    - 'easybib/tests/test_sns.rb'
    - 'php/libraries/config.rb'
    - 'wt-data/libraries/appstodeploy.rb'
    - 'wt-data/tests/test_accessor.rb'
    - 'wt-data/tests/test_dataobject.rb'
