language: ruby

sudo: false

cache: bundler

script:
- bundle exec rake
- make berkshelf

gemfile:
- gemfiles/chef_11.10.gemfile
- gemfiles/chef_12.7.gemfile

before_deploy:
- tar cfz easybib-cookbooks.tar.gz * --exclude=easybib-cookbooks.tar.gz --exclude=vendor/
- mkdir build
- mv easybib-cookbooks.tar.gz build/
- bash MoveBerkshelfArtifacts.sh

deploy:
  - provider: s3
    access_key_id:
      secure: eBI7rBdqays3ahHPsiy0oM6d98tkgvYoKr0ImSWIOFHZYXHHLcSBQhevebNF1PCNrGgvLYkqDn7JWK+f6aqGULxOA4xS4ZhG8O66DA/nAd/vT4eMR7BELohe1QVKNLXj0yr3AJW3K+k8KrAMhhVmU4N1wzvud3/nC+xHZTCveZY=
    secret_access_key:
      secure: MBMxohhv1x9KxZVQCfg3b8kd8T3JmleEAgF/uMWeixt9rfdcggYp/ZHv2jG1V+GIM+kUCGwM4/m82pRxqBqAQ6EUxTmxuR95OhS/vVk2TtUt/UM4edNkzeShMzcswtn4dFemcGi7vPuHUAkf5NwfE2713Iu5o8K1gT9aBxw1tv0=
    bucket: cookbooks.deploy.ezbib.com
    skip-cleanup: true
    region: us-east-1
    local-dir: build
    upload-dir: stable-11-10
    detect_encoding: true
    on:
      branch: stable-chef-11.10
  - provider: s3
    access_key_id:
      secure: eBI7rBdqays3ahHPsiy0oM6d98tkgvYoKr0ImSWIOFHZYXHHLcSBQhevebNF1PCNrGgvLYkqDn7JWK+f6aqGULxOA4xS4ZhG8O66DA/nAd/vT4eMR7BELohe1QVKNLXj0yr3AJW3K+k8KrAMhhVmU4N1wzvud3/nC+xHZTCveZY=
    secret_access_key:
      secure: MBMxohhv1x9KxZVQCfg3b8kd8T3JmleEAgF/uMWeixt9rfdcggYp/ZHv2jG1V+GIM+kUCGwM4/m82pRxqBqAQ6EUxTmxuR95OhS/vVk2TtUt/UM4edNkzeShMzcswtn4dFemcGi7vPuHUAkf5NwfE2713Iu5o8K1gT9aBxw1tv0=
    bucket: cookbooks.deploy.ezbib.com
    skip-cleanup: true
    region: us-east-1
    local-dir: build
    upload-dir: master
    detect_encoding: true
    on:
      branch: master

branches:
  only:
  - master
  - stable-chef-11.10
  - stable
notifications:
  email:
    on_success: never
    on_failure: always
