language: ruby

sudo: false

cache: bundler

script:
- bundle exec rake
- make berkshelf

gemfile:
- gemfiles/chef_11.10.gemfile
- gemfiles/chef_12.7.gemfile

before_deploy:
- tar cfz easybib-cookbooks.tar.gz * --exclude=easybib-cookbooks.tar.gz --exclude=vendor/
- mkdir build
- mv easybib-cookbooks.tar.gz build/
- bash MoveBerkshelfArtifacts.sh

deploy:
  - provider: s3
    secret_access_key:
      secure: ZVOoyvwrNy3Koeb7w6D9+UyjHhwZTfFY8lJSkJ+4So9I9R+z5zNJPAJsUSF/16jpMAMg05zjvhuT1mQgNq68UIoE0kgUuB+gKthJ+mTHMX+La7wNt+THGXw7BjyI+raEH+DhcLWsS2KZkJrn+7pdREZxPmBanBRnPVIq9L0obFs=
    access_key_id:
      secure: nA68RWdYbgRuS6Edzgewt5Z3wPuJcg+QP9nV8T5U730B2eons8+xDGOkFimB5KuWPu9/xV7RznZOP7BcJyFdjYLzJiRWQ+MgMcz+pnlx6yKGV33t1NQ72dof+1JXO2gW644sMC1qkU+RXVmIC1MvXOiv6BWLQehFWTRpgAvASSM=
    bucket:
      secure: A8xm71I3Aq7hMrBTFFwKMPkAeq+K26gDhAYBYNxWpidfig2kbRRzZJIMXqtWh4NKxFnUaJBx7uhWkeL656qzhRObbPsbIrIwEUPWnfYAOnL0FCP4yNteIToIBYc1RqE4DYE6NCIRWO0SVIgSeCv+qAPml2/LWa298hOy1W4LPMc=
    skip-cleanup: true
    local-dir: build
    upload-dir: stable-11-10
    detect_encoding: true
    on:
      branch: stable-chef-11.10
  - provider: s3
    secret_access_key:
      secure: ZVOoyvwrNy3Koeb7w6D9+UyjHhwZTfFY8lJSkJ+4So9I9R+z5zNJPAJsUSF/16jpMAMg05zjvhuT1mQgNq68UIoE0kgUuB+gKthJ+mTHMX+La7wNt+THGXw7BjyI+raEH+DhcLWsS2KZkJrn+7pdREZxPmBanBRnPVIq9L0obFs=
    access_key_id:
      secure: nA68RWdYbgRuS6Edzgewt5Z3wPuJcg+QP9nV8T5U730B2eons8+xDGOkFimB5KuWPu9/xV7RznZOP7BcJyFdjYLzJiRWQ+MgMcz+pnlx6yKGV33t1NQ72dof+1JXO2gW644sMC1qkU+RXVmIC1MvXOiv6BWLQehFWTRpgAvASSM=
    bucket:
      secure: A8xm71I3Aq7hMrBTFFwKMPkAeq+K26gDhAYBYNxWpidfig2kbRRzZJIMXqtWh4NKxFnUaJBx7uhWkeL656qzhRObbPsbIrIwEUPWnfYAOnL0FCP4yNteIToIBYc1RqE4DYE6NCIRWO0SVIgSeCv+qAPml2/LWa298hOy1W4LPMc=
    skip-cleanup: true
    local-dir: build
    upload-dir: master
    detect_encoding: true
    on:
      branch: master

branches:
  only:
  - master
  - stable-chef-11.10
  - stable

notifications:
  email:
    on_success: never
    on_failure: always