language: ruby

sudo: false

cache: bundler

script:
- bundle exec rake
- make berkshelf

gemfile:
- gemfiles/chef_11.10.gemfile
- gemfiles/chef_12.7.gemfile

before_deploy:
- tar cfz easybib-cookbooks.tar.gz * --exclude=easybib-cookbooks.tar.gz --exclude=vendor/
- mkdir build
- mv easybib-cookbooks.tar.gz build/
- bash MoveBerkshelfArtifacts.sh

deploy:
  - provider: s3
  secret_access_key:
    secure: oIPsgHHsPLjEpM00ne2GNtmaTwBuxgBtNLYVyUWwr4E1Bvu717mccREmVgqK4bvNUcaNQmtoXHEik1X9zO8y53081y5ANwonlI48EpRhk8UdhuURpVUqJOxYkUYk/KMnRE3nKZ17BmauoRdY2onR/j5CXrgXVkMBRBv4GXJyc1M=
  access_key_id:
    secure: LQwVNX5gZkfOhVlvc+NPUUOlHGVhP1PtNKTA9MqmOAkxyqCU1E7BsuECzDJquLM2fj6sgGJb7rzYOaAWSgnD4932qxr2l54qx+mlrkHGai0ThMS4Nt5+hcppN1/KWSTbxcbViNcz3bsnyPSqh3Gp7r3IskqgLFJhK3vaEIYAq5w=
  bucket:
    secure: iixlbTzCeMLngkQsqRpoWm9N259x/7HUOvZtQvrw3ETtf+yGG2fZR6LttyqEGr3lNVGJMLclbb84OXcrnDGSvDuR8MTRPciLz6BOfFMg6D0uyINLQPGw6dbxXHVZ9azNSCySjXcAJqHdT+Q6DEsR9NkrMgTk6fjooyWabgQXHc8=
    skip-cleanup: true
    local-dir: build
    upload-dir: stable-11-10
    detect_encoding: true
    on:
      branch: stable-chef-11.10
  - provider: s3
  secret_access_key:
    secure: oIPsgHHsPLjEpM00ne2GNtmaTwBuxgBtNLYVyUWwr4E1Bvu717mccREmVgqK4bvNUcaNQmtoXHEik1X9zO8y53081y5ANwonlI48EpRhk8UdhuURpVUqJOxYkUYk/KMnRE3nKZ17BmauoRdY2onR/j5CXrgXVkMBRBv4GXJyc1M=
  access_key_id:
    secure: LQwVNX5gZkfOhVlvc+NPUUOlHGVhP1PtNKTA9MqmOAkxyqCU1E7BsuECzDJquLM2fj6sgGJb7rzYOaAWSgnD4932qxr2l54qx+mlrkHGai0ThMS4Nt5+hcppN1/KWSTbxcbViNcz3bsnyPSqh3Gp7r3IskqgLFJhK3vaEIYAq5w=
  bucket:
    secure: iixlbTzCeMLngkQsqRpoWm9N259x/7HUOvZtQvrw3ETtf+yGG2fZR6LttyqEGr3lNVGJMLclbb84OXcrnDGSvDuR8MTRPciLz6BOfFMg6D0uyINLQPGw6dbxXHVZ9azNSCySjXcAJqHdT+Q6DEsR9NkrMgTk6fjooyWabgQXHc8=
    skip-cleanup: true
    local-dir: build
    upload-dir: master
    detect_encoding: true
    on:
      branch: master

branches:
  only:
  - master
  - stable-chef-11.10
  - stable

notifications:
  email:
    on_success: never
    on_failure: always